# Generated by Django 5.2.8 on 2025-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=40)),
                ('source', models.CharField(choices=[('operator', 'Operator'), ('monitoring', 'Monitoring'), ('partner', 'Partner')], default='operator', max_length=40)),
            ],
        ),
    ]
