# Generated by Django 5.2.8 on 2025-11-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostsignal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allert',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=40),
        ),
    ]
